[package]
name = "gcp"
version = "0.1.0"
edition = "2024"

[dependencies]
# CLI and argument parsing
clap = { version = "4.5", features = ["derive", "env", "color"] }

# HTTP operations
reqwest = { version = "0.12", features = ["json", "stream"] }
tokio = { version = "1", features = ["full"] }

# GitHub API
octocrab = "0.47.0"

# URL and path handling
url = "2.5"
dirs = "6.0.0"  # For config/cache directories

# Error handling and logging
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
thiserror ="2.0.17"

# Serde support
serde = { version = "1.0", features = ["derive"] }

# Progress reporting
indicatif = "0.18.0"

# File operations
tempfile = "3.8"

# Time handling
chrono = { version = "0.4", features = ["serde"] }

# Base64 encoding/decoding
base64 = "0.22"
base64-simd = "0.8"

# JSON support
serde_json = "1.0"
